### ISSUE TITLE
Maxlength clamping causes field to be marked invalid

### ISSUE THREAD

**Issue by Captnwalker1** [nogorilla/angular-cc-library#10]
If you enter a credit card that is too long ( say the test card 4111 1111 1111 1111), if you just keep spamming the 1s when it hits max length it will remove any excess characters at the end, but the field is still marked invalid, and to work around you have to remove the last digit and re-enter it.

**Comment by yogeshbansal** [comment]
The above issue still exist mentioned by @Captnwalker1 . The length of card will be 17, even though it will be showing 16 digit in the field. @nogorilla

**Comment by CasanovaGregory** [comment]
Hi, I experienced it too.
I'll fix this as soon as possible !

**Comment by mfalade** [comment]
Any word on this fix yet @CasanovaGregory ?
I'm experiencing the same issue.

**Comment by mfalade** [comment]
I have opened a pull request to address the issue described above [here](https://github.com/nogorilla/angular-cc-library/pull/18).


cc @CasanovaGregory @nogorilla

**Comment by nogorilla** [comment]
Thanks @mfalade
