### ISSUE TITLE
Backspace with american express or diners club stop and keep first 2 digits

### ISSUE THREAD

**Issue by almothafar** [nogorilla/angular-cc-library#13]
When you use American card number start with 37 or 377 or diners club with 36 as for example, and erase it using backspace, it does not work on until the end, it stuck on undeletable 37 or 377.

**Comment by nogorilla** [comment]
@almothafar do you have an example number that I can test with? I'm using test numbers from [paypal](https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm) and [stripe](https://stripe.com/docs/testing) and cannot recreate your issue

**Comment by almothafar** [comment]
@nogorilla you type number or copy/paste? I'm just typing the card number by number, not copy/paste.

I got the code and fixed the `formatBackCardNumber(e)` method with adding an extra condition:

```
    if (/\d\s+$/.test(value)) {
      e.preventDefault();
      setTimeout(() => {
        this.target.value = value.replace(/\d\s+$/, '');
      });
    } else if (/\s\d$/.test(value)) {
      e.preventDefault();
      setTimeout(() => {
        this.target.value = value.replace(/\s\d$/, '');
      });
    } else if (/\s\d?$/.test(value)) {
      e.preventDefault();
      setTimeout(() => {
        this.target.value = value.replace(/\s$/, '');
      });
    }
```

The problem seems when I type 37 the card got extra space after until I type another number, like 377  then the issue stay when I try to "backspace" the space removed then added again.

Also, I removed `@HostListener('paste', ['$event'])` and `@HostListener('change', ['$event'])`  because got issues with auto refill from browser and with copy/pase.

**Comment by Sharonpammi** [comment]
Hi @nogorilla, Credit card is validated only when I am trying to copy and paste a number. If I type the same number, the credit card number is not validated. For example, I used these sample credit card numbers (in the link below) to verify validation, which works only when I copy paste those numbers. 
http://www.easy400.net/js2/regexp/ccnums.html

 Could you help me resolve this?

**Comment by Sharonpammi** [comment]
I take it back. Only visa credit cards are not validated. Credit-card.ts file contains visa as available card types that are supported. However it doesn't work for me. Any inputs?
