### ISSUE TITLE
Expiry date format as MM/YY

### ISSUE THREAD

**Issue by mtina007** [nogorilla/angular-cc-library#17]
Hi,
I want to have MM/YY , but i get only MM/YYYY below is my code
``` 
<label for="cc-exp-date">Expiry Date</label>
          <input  formControlName="cardDate" class="form-control"
                  id="cc-exp-date" type="tel" ccExp/>
<span *ngIf="!purchaseForm.get('cardDate').valid && purchaseForm.get('cardDate').touched">
      Please enter expiry date
        </span>
```

`'cardDate': new FormControl(null, [CreditCardValidator.validateExpDate,Validators.required])`

**Comment by nogorilla** [comment]
@mtina007 not sure I understand the problem - Date validator supports both MM/YY or MM/YYYY and can switch between the two formats automatically

**Comment by mtina007** [comment]
When I used the date validator; if I put MM/YY the form will be invalid, but not for MM/YYYY.
it seems it does not switch automatically

**Comment by subramaniashiva** [comment]
Hi @mtina007 , Did you add the form validation in the typescript file as well? Can you please share your code so that it will be easier for us?

**Comment by carloscasal** [comment]
Ended up watching for the `keyup` event and resetting input value from there.
