### ISSUE TITLE
It doesn't support some card number combinations 

### ISSUE THREAD

**Issue by gribchic** [nogorilla/angular-cc-library#21]
I've noticed in the file "credit-card.ts" this code
`{
    type: 'jcb',
    patterns: [35],
    format: defaultFormat,
    length: [16],
    cvvLength: [3],
    luhn: true
  }`
but I've found a next information:

> JCB: ^(?:2131|1800|35[0-9]{3})[0-9]{3,}$ JCB cards begin with 2131, 1800 or 35.
[Credit card type](https://stackoverflow.com/questions/72768/how-do-you-detect-credit-card-type-based-on-number)

**Comment by nogorilla** [comment]
@gribchic I can find no other documentation that lists JCB card formats starting with anything other than [35](https://en.wikipedia.org/wiki/Payment_card_number)

I will in to bet that the SO question your linked was valid at one time but JCB may have changed it's formation. The SO question was answered nearly 10 years ago. If you can find anymore documentation, I will reopen this issue.

I did find that JCB supports 19 digit cards and I will update according.
