### ISSUE TITLE
Working with Ionic 

### ISSUE THREAD

**Issue by ThomasKientz** [nogorilla/angular-cc-library#26]
Has anyone managed to use it with Ionic ?

I have imported every modules as I'm used to do, but the directive has no affect at all. 

I'm using a regular <input>, not the <ion-input>.

**Comment by aokoruyucu** [comment]
can you ? in my case, its throwing an error 'Cannot read property 'split' of undefined' any idea?

**Comment by thekip** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!

**Comment by jongbonga** [comment]
I can confirm it was working on Ionic until version 2 update

**Comment by ahmedelatab** [comment]
This library supports ion-input!

https://www.npmjs.com/package/angularx-cc-library/v/1.1.5

**Comment by thekip** [comment]
> https://www.npmjs.com/package/angularx-cc-library/v/1.1.5
Last published 4 years ago... 

If someone figured out what should be done to make it compatible with ionic i will be happy to incorporate it into this library.

**Comment by ahmedelatab** [comment]
> > https://www.npmjs.com/package/angularx-cc-library/v/1.1.5
> > Last published 4 years ago...
> 
> If someone figured out what should be done to make it compatible with ionic i will be happy to incorporate it into this library.

Even it is published 4 years ago, it is working fine, and you can test it on your own app to figure out any essential features missing!

At least, card number and expiry date is working without any problems...

**Comment by jongbonga** [comment]
What's the problem with this plugin? 

This is a 2017 issue and the plugin works fine with Ionic, why was it reopened?

**Comment by ahmedelatab** [comment]
> What's the problem with this plugin?
> 
> This is a 2017 issue and the plugin works fine with Ionic!

It doesn't work with `ion-input`. This is the only problem I think.

But it solved by this library: https://www.npmjs.com/package/angularx-cc-library/v/1.1.5

**Comment by jongbonga** [comment]
> > What's the problem with this plugin?
> > This is a 2017 issue and the plugin works fine with Ionic!
> 
> It doesn't work with `ion-input`. This is the only problem I think.
> 
> But it is solved by this library: https://www.npmjs.com/package/angularx-cc-library/v/1.1.5

I'm on version `2.1.2` and it's working fine for me
