### ISSUE TITLE
validateCCNumber IE browser compatibility issues

### ISSUE THREAD

**Issue by ybeunard** [nogorilla/angular-cc-library#27]
The validator validateCCNumber is not compatible with IE because he use String.prototype.includes.

Need replace this function by indexOf() !== -1

**Comment by ganeshmuthuvelu** [comment]
Is this still an issue or it was just a case of missing the required polyfills?

**Comment by ybeunard** [comment]
Hello

Sorry for the long response time.
We corrected the problem on our side by the use of a polyfills but I still wanted to prevent.
I close it now.

Thanks
