### ISSUE TITLE
What's the intent of the "cc-brand" class?

### ISSUE THREAD

**Issue by ganeshmuthuvelu** [nogorilla/angular-cc-library#29]
In the sample project, there's a "cc-brand" class
`[<span class="cc-brand"></span>]`

What's the purpose of it? I was hoping it would show the appropriate image based on the card type - but it doesn't and I was wondering it's intent.. Please let me know.

**Comment by thekip** [comment]
I updated the demo project, and now it shows cc schema in this field. 
Also there is a feature request to extend `ccDirective` and allow retrieving parsed ccType from it https://github.com/nogorilla/angular-cc-library/issues/45
