### ISSUE TITLE
How to pass the card type to the controller (from .html to .ts file with in the component )

### ISSUE THREAD

**Issue by thom7kick** [nogorilla/angular-cc-library#3]

**Comment by nogorilla** [comment]
Use the `cardFromNumber` function from the shared [CreditCard](https://github.com/nogorilla/angular-cc-library/blob/master/src/shared/credit-card.ts#L82) class. 

so in your controller, you'd call
```javascript
let cardType = CreditCard.cardFromNumber(cardNumber);
```
