### ISSUE TITLE
Extra digit on iPhone

### ISSUE THREAD

**Issue by venoby** [nogorilla/angular-cc-library#32]
card number:
When typing e.g. **5100** on iPhone (chrome, safari)
The result will be **5100 0** (the 4th digit is entered twice)

**update:**
fixed in [PR](https://github.com/nogorilla/angular-cc-library/pull/31) by @jribble

**Comment by mdbarr73** [comment]
Same issue here on iPad. Chrome or Safari.

**Comment by gavmck** [comment]
Looks merged and fixed in 1.2.4 to me.

**Comment by nirmal-mobiquity** [comment]
I think it should be closed, as commented by @gavmck updating library resolves issue
