### ISSUE TITLE
Feature request: emit credit card brand name as an event

### ISSUE THREAD

**Issue by angelkenneth** [nogorilla/angular-cc-library#36]
Add `@Ouput()` to the directive to emit the indentified credit card brand, ie. like below:

```html
<input matInput formControlName="number" placeholder="Card Number"
    type="tel" autocomplete="cc-number" ccNumber required (onCardType)="doStuff($event)"/>
```

Right now, credit card brand is assigned as a class, so one needs to cycle through the possible brand classes, like so: 

```typescript
  @ViewChild(CreditCardFormatDirective) ccCardInput: CreditCardFormatDirective;

  get cardBrand() {
    if (!this.ccCardInput) {
      return;
    }

    const input = <HTMLInputElement>this.ccCardInput.target;
    const cards = CreditCard.cards();

    if (input.classList.contains('identified')) {
      for (const c of cards) {
        if (input.classList.contains(c.type)) {
          return c.type;
        }
      }
    }
  }
```

**Comment by thekip** [comment]
There is a different ways to achieve the same functionality,  one of them is implementing `exportAs: ` in `ccCard` directive which is already requested here https://github.com/nogorilla/angular-cc-library/issues/45

Another one is using `CreditCard` class as described in aforementioned issue, so i close this issue as duplicate.
