### ISSUE TITLE
ccNumber directive is only returning first four for control value, making validateCCNumber return that the field is invalid

### ISSUE THREAD

**Issue by aarmora** [nogorilla/angular-cc-library#55]
Here's a stackblitz with the example - https://stackblitz.com/edit/angular-sdsgck

With a log [here](https://github.com/nogorilla/angular-cc-library/blob/37c9ae1c8086412c2938e04e5675514e65cc9af8/src/credit-card.validator.ts#L9), `control.value` is always only the first four digits. I haven't been able to find where in the directive this is happening (everywhere I log has all the digits as expected) but with the directive removed, `validateCCNumber` works great.

Will update as I find more.

**Comment by thekip** [comment]
In your stackblitz example, you have `type='number'` and `type='tel'` on your input. 
Remove them and put type="text". 

Probably problem not in the library itself, but in angular or browser behaviour, with this attributes it doesn't accept spaces as value in model.

**Comment by thekip** [comment]
Problem not related to library itself, if you still think this is a library mistake, please create a new issue with a detailed description.
