### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by nogorilla** [nogorilla/angular-cc-library#62]
Looking for help to maintain or take ownership of this project. I no longer work with Angular so I do not use or keep up with any changes. As many still use this library, I'm happy to let it go to someone else who has the time and ability to keep it active.

**Comment by evansmwendwa** [comment]
Hi @nogorilla I am interested in keeping this project alive and updated. I can help in maintaining the project

**Comment by nogorilla** [comment]
@evansmwendwa thanks, just added you as a collaborator. I'll working on updating NPM as well

**Comment by evansmwendwa** [comment]
Thanks for the good work. I will try and add ivy support in the coming days

**Comment by thekip** [comment]
@evansmwendwa how it's going? I'm going to port it latest angular right now because I need it asap on our project

**Comment by evansmwendwa** [comment]
Go ahead and let me know if you need assistance

**Comment by thekip** [comment]
done, https://github.com/nogorilla/angular-cc-library/pull/64

**Comment by nogorilla** [comment]
@evansmwendwa just gave you maintainer access on NPM, can you confirm?

**Comment by evansmwendwa** [comment]
Got it. Thanks

**Comment by thekip** [comment]
@evansmwendwa when you a going to spend a time and check/merge my PR? Maybe it's better to give me contributor access as well, because i'm going to create few more PR's soon, and resolve couple existing bugs/feature requests.

**Comment by thekip** [comment]
@evansmwendwa @nogorilla guys, don't want to be rude but want to push you to check PR and merge it, people are waiting. 
@evansmwendwa you had to think before taking responsibility if you have no time for it.

**Comment by evansmwendwa** [comment]
@thekip I don't mean to rude here but I will have a look at it when I do. If you feel blocked I suggest you either request to be a maintainer also, use your fork or go proprietary. Among OSS rights, time is not one of them

**Comment by thekip** [comment]
> If you feel blocked I suggest you either request to be a maintainer also

I did it 4 days ago:

>  Maybe it's better to give me contributor access as well, because i'm going to create few more PR's soon

**Comment by thekip** [comment]
Well, let's do it in different way, @nogorilla please give me maintainer access for this repo and npm.

**Comment by nogorilla** [comment]
@thekip what's your npm username?

**Comment by thekip** [comment]
https://www.npmjs.com/settings/thekip/profile

**Comment by nogorilla** [comment]
getting a 404 error for that page

**Comment by thekip** [comment]
seems it is a private page, doesn't matter, account name is `thekip`

**Comment by nogorilla** [comment]
just to confirm: https://www.npmjs.com/~thekip

**Comment by thekip** [comment]
yep

**Comment by thekip** [comment]
Thanks, got it. PR is merged, continue working on the project. 👍
