### ISSUE TITLE
v2 broke compatibilty with Ionic 

### ISSUE THREAD

**Issue by jongbonga** [nogorilla/angular-cc-library#66]
the v2 update broke compatibility with Ionic as commented on [#26 ](https://github.com/nogorilla/angular-cc-library/issues/26#issuecomment-606642237)

### v1.2.5 
with `ion-input`
![Screenshot_2020-03-31 Lula Commuter(1)](https://user-images.githubusercontent.com/12111716/78037596-0ec9f480-736c-11ea-9e01-1992752a3586.png)

### v2.0.0 
Directives have no effect on `ion-input` but work well on `input`
![Screenshot_2020-03-31 Lula Commuter(2)](https://user-images.githubusercontent.com/12111716/78037869-636d6f80-736c-11ea-9662-7b1e3fe598f6.png)

**Comment by thekip** [comment]
Well, I know where is the problem, I will fix soon.
